version: "3.9"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: pytest_runner
    env_file:
      - .env.test
    depends_on:
      - test_db
      - redis
    networks:
      - testnet
    volumes:
      - .:/app

  test_db:
    image: postgres:16
    container_name: test_postgres
    env_file:
      - .env.test
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - testnet

  redis:
    image: redis:7
    networks:
      - testnet

networks:
  testnet:

volumes:
  test_postgres_data:
